stolostron/managedcluster-import-controller

Makefile, pkg/controller/managedcluster/import_manifestwork.go, pkg/controller/managedcluster/import_manifestwork_test.go, pkg/controller/managedcluster/import_secret.go, pkg/controller/managedcluster/import_secret_test.go, pkg/controller/managedcluster/import_syncset.go, pkg/controller/managedcluster/import_syncset_test.go, pkg/controller/managedcluster/import_yamls.go, pkg/controller/managedcluster/managedcluster_controller.go, pkg/controller/managedcluster/managedcluster_import_detach.go, pkg/controller/managedcluster/managedcluster_import_detach_test.go
- added back lint in `make check`
- removed unused parameter & commented code to pass lint
Note: manually executed functional tests locally, and passed
=> fix lint issues

.gitignore, pkg/controller/managedcluster/managedcluster_controller.go, pkg/controller/managedcluster/managedcluster_import_detach.go, test/functional/managedcluster_test.go
=> Fix auto-import-secret deletion

.github/workflows/functional-tests.yml, Makefile, build/check-copyright.sh, build/copyright-header.txt
=> Add check-copyright

Makefile, build/run-functional-tests.sh, go.mod, go.sum, pkg/controller/managedcluster/managedcluster_controller.go, pkg/controller/managedcluster/managedcluster_controller_test.go, pkg/controller/managedcluster/managedcluster_import_detach.go, test/functional/managedcluster_import_controller_suite_test.go, test/functional/managedcluster_test.go
https://github.com/open-cluster-management/backlog/issues/10850
=> Add finlizer on clusterDeployment to fix BM

.copyrightignore, CODE_OF_CONDUCT.md, CONTRIBUTING.md, MISSION.md, build/check-copyright.sh
=> Add comment on contributing + conduct

pkg/controller/managedcluster/managedcluster_controller.go
=> Add check if pods in ns before delete

Makefile, build/run-functional-tests.sh, deploy/kustomization.yaml, deploy/role.yaml, deploy/role_binding.yaml, pkg/controller/managedcluster/managedcluster_controller.go
=> Fix func tests rbac/err if failed to set mc cond

pkg/controller/managedcluster/import_manifestwork.go
issue: https://github.com/open-cluster-management/backlog/issues/11280
=> fix list mw with namespace

pkg/controller/csr/csr_controller.go, pkg/controller/managedcluster/import_manifestwork.go, pkg/controller/managedcluster/managedcluster_controller.go, pkg/controller/managedcluster/managedcluster_import_detach.go
=> Optimize processing if cd not yet installed

build/Dockerfile
Signed-off-by: Leena Jawale <ljawale@redhat.com>
issue: https://github.com/open-cluster-management/backlog/issues/11338
=> update base docker image

Makefile, deploy/deployment.yaml, overlays/community/deployment.yaml, overlays/community/kustomization.yaml, overlays/test/with_sha/deployment.yaml
Signed-off-by: Hanqiu Zhang <hanzhang@redhat.com>
=> add community deploy

build/run-functional-tests.sh, docs/development.md, overlays/test/with_sha/deployment.yaml
=> Fix kubectl versioning

.copyrightignore, .gitignore, pkg/controller/managedcluster/envtest_test.go, pkg/controller/managedcluster/managedcluster_controller_test.go, pkg/controller/managedcluster/managedcluster_import_detach_test.go
=> Fix unit-test self-import and add extra unit-tests

pkg/controller/managedcluster/import_secret.go
https://github.com/open-cluster-management/backlog/issues/11178
=> put v1 in the crds.yaml

pkg/controller/managedcluster/import_secret.go
=> Rollback v1

pkg/controller/managedcluster/import_secret.go, pkg/controller/managedcluster/managedcluster_controller.go
https://github.com/open-cluster-management/backlog/issues/10465
=> Do not delete ns with non curator pod

pkg/controller/csr/csr_manager.go
=> Add CSR delete/generic predicate

go.mod, go.sum
Signed-off-by: Hanqiu Zhang <hanzhang@redhat.com>
Hive 1.1.3
https://github.com/openshift/hive/commit/5c038fb051906a7c2d733e7b017690044c66c124
=> update hive api

pkg/controller/managedcluster/managedcluster_controller.go
=> reduce reconcile time

pkg/controller/managedcluster/managedcluster_controller.go
=> Use Patch to add finalizer

build/Dockerfile, build/Dockerfile-coverage
=> Update operator name

.github/workflows/functional-tests.yml, build/Dockerfile, pkg/controller/managedcluster/bootstrap_sa.go
https://github.com/open-cluster-management/backlog/issues/13251
/hold
=> Fix prefix check length

pkg/controller/managedcluster/managedcluster_controller.go, test/functional/managedcluster_test.go
https://github.com/open-cluster-management/backlog/issues/13339
https://github.com/open-cluster-management/backlog/issues/13365
/hold
=> Add business logic for created_via annotation

pkg/controller/managedcluster/managedcluster_controller.go
https://github.com/open-cluster-management/backlog/issues/13631
/hold
=> Add both crd on mw

pkg/controller/managedcluster/managedcluster_controller.go
=> Check if pod not ansible

go.mod, go.sum, test/functional/resources/hive_v1_clusterdeployment_crd.yaml
https://github.com/open-cluster-management/backlog/issues/14856
=> upgrade hive to 1.1.12

cmd/manager/main.go, pkg/controller/csr/csr_controller.go, pkg/controller/csr/csr_controller_test.go, pkg/controller/csr/csr_manager.go, test/functional/managedcluster_import_controller_suite_test.go, test/functional/managedcluster_test.go
issue https://github.com/open-cluster-management/backlog/issues/15363
=> upgrade certificate to v1

.gitignore
=> ignore temp dirs and files

pkg/constants/constants.go, pkg/helpers/helpers.go, pkg/helpers/helpers_test.go
=> update helpers methods

.copyrightignore
=> skip copyright for manifest files

pkg/controller/cluster/managedcluster_controller.go, pkg/controller/cluster/managedcluster_controller_test.go, pkg/controller/cluster/manager.go
=> [refactor] add managedcluster-controller

pkg/controller/selfmanagedcluster/manager.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller_test.go
=> [refactor] add selfmanagedcluster-controller

pkg/controller/manifestwork/manager.go, pkg/controller/manifestwork/manifestwork_controller.go, pkg/controller/manifestwork/manifestwork_controller_test.go
=> [refactor] add manifestwork-controller

test/e2e/autoimport_test.go, test/e2e/clusterdeployment_test.go, test/e2e/csr_test.go, test/e2e/e2e_suite_test.go, test/e2e/managedcluter_test.go, test/e2e/selfmanagedcluster_test.go, test/e2e/util/util.go
=> [refactor] add e2e test cases

.gitignore, pkg/controller/autoimport/autoimport_controller.go, pkg/controller/autoimport/autoimport_controller_test.go, pkg/controller/autoimport/manager.go, pkg/helpers/helpers.go
=> [refactor] add autoimport-controller

pkg/constants/constants.go, pkg/controller/cluster/managedcluster_controller.go, pkg/controller/cluster/managedcluster_controller_test.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/manager.go, pkg/helpers/helpers.go
=> [refactor] add clusterdeployment-controller

go.mod, go.sum
https://github.com/open-cluster-management/backlog/issues/15987
=> upgrade hive to 1.1.16

pkg/controller/managedcluster/managedcluster_controller.go, test/e2e/managedcluter_test.go
=> Set the cluster name label if it is empty

build/Dockerfile, go.mod
=> update go to 1.17

deploy/base/deployment.yaml, pkg/controller/importconfig/manifests/klusterlet/operator.yaml
issue: https://github.com/open-cluster-management/backlog/issues/17898
=> change imagePullPolicy to IfNotPresent

go.mod, go.sum
=> update crypto (2.4)

go.mod, go.sum
=> update crypto (2.3)

pkg/controller/managedcluster/managedcluster_controller.go
=> using claim as the cluster name label

build/run-e2e-tests.sh, pkg/controller/clusterdeployment/clusterdeployment_controller.go, test/e2e/clusterdeployment_test.go, test/e2e/util/util.go
=> delete the cluster namespace, even the provision failed

build/run-e2e-tests.sh
=> Fix flaky e2e test

Makefile, go.mod, go.sum, hack/copy-crds.sh, pkg/controller/importconfig/manifests/klusterlet/crds/klusterlets.crd.v1.yaml, pkg/controller/importconfig/manifests/klusterlet/crds/klusterlets.crd.v1beta1.yaml, pkg/controller/importconfig/manifests/klusterlet/klusterlet.yaml
=> Upgrade klusterlet api for detached mode

pkg/controller/importconfig/importconfig_controller_test.go, pkg/controller/importconfig/worker_default.go, pkg/helpers/helpers.go
=> fix: create agent namespace first

go.mod, pkg/controller/managedcluster/managedcluster_controller.go
=> maintain the cluster name label

pkg/controller/managedcluster/managedcluster_controller.go
=> [release-2.4] maintain the cluster name label

go.mod, go.sum, pkg/controller/importconfig/manifests/klusterlet/crds/klusterlets.crd.v1.yaml, pkg/controller/importconfig/manifests/klusterlet/crds/klusterlets.crd.v1beta1.yaml
Related issue: https://github.com/stolostron/backlog/issues/20107
=> update klusterlet CRD

pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/importconfig_controller_test.go, pkg/controller/importconfig/manifests/klusterlet/image_pull_secret.yaml, pkg/controller/importconfig/worker_default.go
fix issue: 
https://github.com/stolostron/backlog/issues/20219
https://github.com/stolostron/backlog/issues/18580
=> correct the type of secrets

pkg/controller/importconfig/cluster_info.go
issue: https://github.com/stolostron/backlog/issues/20219
=> release 2.4: remove check the type of cluster api secret

go.mod, go.sum
Signed-off-by: ldpliu <daliu@redhat.com>
=> upgrade hive

go.mod, go.sum
Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/stolostron/backlog/issues/19686
=> update hive in 2.4

pkg/controller/manifestwork/manifestwork_controller.go, test/e2e/selfmanagedcluster_test.go
issue: https://github.com/stolostron/backlog/issues/20474
=> wait for the addon manifestworks to be deleted

pkg/helpers/manifestwork.go
=> avoid to add finalizer to manifestworks if the cluster is deleting

docs/klusterlet_detached_import.md, docs/klusterlet_hosted_import.md
=> Add doc for klusterlet detached mode

pkg/controller/importconfig/manifests/klusterlet/operator.yaml
=> add disable-leader-election flag to klusterlet operator

pkg/controller/autoimport/autoimport_controller.go, pkg/controller/hosted/controller.go, pkg/helpers/autoimport.go, test/e2e/autoimport_test.go
=> add auto-import-secret annotation to keep the secret

deploy/base/deployment.yaml, pkg/controller/autoimport/autoimport_controller.go, test/e2e/autoimport_test.go, test/e2e/imageregistry_test.go
=> [release-2.4] add auto-import-secret annotation to keep the secret

pkg/controller/hosted/controller.go, pkg/controller/hosted/manager.go
=> force delete all works in hosted mode

pkg/controller/autoimport/autoimport_controller.go, pkg/controller/autoimport/autoimport_controller_test.go
=> fix no indication when automatic cluster import has failed

pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/cluster_info_test.go, pkg/controller/importconfig/importconfig_controller.go
fix issue: https://github.com/stolostron/backlog/issues/21634
=> [release 2.4]fix the length of sa name is over 63

pkg/helpers/helpers.go
fix the issue: https://github.com/stolostron/backlog/issues/21723
=> fix the addon is not foce deleted

pkg/helpers/imageregistry/client.go, pkg/helpers/imageregistry/client_test.go
=> fix nil cluster and add more ut

deploy/base/clusterrole.yaml, go.sum, pkg/controller/hosted/controller.go, pkg/controller/managedcluster/managedcluster_controller.go, pkg/controller/managedcluster/managedcluster_controller_test.go, pkg/controller/manifestwork/manager.go, pkg/controller/manifestwork/manifestwork_controller.go, pkg/controller/manifestwork/manifestwork_controller_test.go, pkg/helpers/helpers.go, pkg/helpers/manifestwork.go, test/e2e/cleanup_test.go, test/e2e/e2e_suite_test.go, test/e2e/util/util.go
issue reference: https://github.com/stolostron/backlog/issues/21835
=> Delete addons while detaching clusters

go.mod, go.sum
=> [release-2.4] fix cve-2022-29810

.github/workflows/e2e-tests.yml, Makefile, build/Dockerfile, build/golangci.yml, build/run-lint-check.sh, go.mod
Signed-off-by: xuezhaojun <zxue@redhat.com>
https://github.com/stolostron/backlog/issues/22707
=> Update go 1.18

build/golangci.yml, go.mod, pkg/controller/importconfig/importconfig_controller_test.go, pkg/controller/importconfig/manager.go, pkg/controller/importconfig/manifests/klusterlet/klusterlet.yaml, pkg/controller/importconfig/manifests/klusterlet/operator.yaml, pkg/controller/importconfig/worker_default.go, pkg/controller/importconfig/worker_detached.go, pkg/controller/importconfig/worker_factory.go, pkg/helpers/helpers.go, pkg/helpers/helpers_test.go, test/e2e/e2e_suite_test.go, test/e2e/klusterletplacement_test.go, test/e2e/util/util.go
=> supporting to configure nodeSelector/tolerations for klusterlet

pkg/constants/constants.go, pkg/controller/importconfig/importconfig_controller.go, pkg/controller/importconfig/importconfig_controller_test.go, pkg/controller/importconfig/worker_default.go, pkg/controller/importconfig/worker_detached.go
Related issue: https://github.com/stolostron/backlog/issues/23554
Signed-off-by: Yang Le <yangle@redhat.com>
=> support customizing klusterlet ns with annotation

pkg/controller/hosted/controller.go, pkg/controller/hosted/controller_test.go, pkg/controller/hosted/manager.go, pkg/controller/importconfig/importconfig_controller_test.go, pkg/helpers/manifestwork.go
Signed-off-by: xuezhaojun <zxue@redhat.com>
https://github.com/stolostron/backlog/issues/22701
=> Add test cases for hosted controller

pkg/controller/importconfig/cluster_info.go
=> support kube 1.24 sa secret changes

pkg/controller/importconfig/cluster_info.go
=> correct the log format

pkg/constants/constants.go, pkg/controller/autoimport/autoimport_controller.go, pkg/controller/autoimport/autoimport_controller_test.go, pkg/controller/autoimport/manager.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/manager.go, pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/manifests/klusterlet/crds/klusterlets.crd.v1.yaml, pkg/controller/manifestwork/manager.go, pkg/controller/manifestwork/manifestwork_controller.go, pkg/controller/manifestwork/manifestwork_controller_test.go, pkg/controller/selfmanagedcluster/manager.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller_test.go, pkg/helpers/helpers.go, pkg/helpers/helpers_test.go, test/e2e/autoimport_test.go, test/e2e/cleanup_test.go, test/e2e/clusterdeployment_test.go, test/e2e/e2e_suite_test.go, test/e2e/klusterletplacement_test.go, test/e2e/selfmanagedcluster_test.go
=> avoid delete klusterlet on the managed cluster

pkg/constants/constants.go, pkg/controller/autoimport/autoimport_controller.go, pkg/controller/autoimport/autoimport_controller_test.go, pkg/controller/autoimport/manager.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/manager.go, pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/manifests/klusterlet/crds/klusterlets.crd.v1.yaml, pkg/controller/manifestwork/manager.go, pkg/controller/manifestwork/manifestwork_controller.go, pkg/controller/manifestwork/manifestwork_controller_test.go, pkg/controller/selfmanagedcluster/manager.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller_test.go, pkg/helpers/helpers.go, pkg/helpers/helpers_test.go, test/e2e/autoimport_test.go, test/e2e/cleanup_test.go, test/e2e/clusterdeployment_test.go, test/e2e/e2e_suite_test.go, test/e2e/selfmanagedcluster_test.go
=> [backplane-2.0] avoid delete klusterlet on the managed cluster

build/run-e2e-tests.sh, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusternamespacedeletion/controller.go, pkg/controller/clusternamespacedeletion/controller_test.go, pkg/controller/clusternamespacedeletion/manager.go, pkg/controller/clusternamespacedeletion/suite_test.go, pkg/controller/controller.go, pkg/controller/managedcluster/managedcluster_controller.go, pkg/controller/managedcluster/managedcluster_controller_test.go, test/e2e/cleanup_test.go, test/e2e/resources/assisted-service/agent-install.openshift.io_infraenvs.yaml, test/e2e/resources/ocm/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml, test/e2e/resources/ocm/0000_01_addon.open-cluster-management.io_managedclusteraddons.crd.yaml
Signed-off-by: Jian Qiu <jqiu@redhat.com>
=> add ns deletion controller

build/run-e2e-tests.sh, deploy/base/clusterrole.yaml, pkg/constants/constants.go, pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/cluster_info_test.go, pkg/controller/importconfig/importconfig_controller_test.go, pkg/controller/importconfig/worker_default.go, pkg/controller/importconfig/worker_detached.go, test/e2e/util/util.go
=> using tokenrequest to request bootstrap token

test/e2e/e2e_suite_test.go, test/e2e/manuallyimport_test.go
issue reference: https://github.com/stolostron/backlog/issues/20081
=> Add e2e test for manually import a cluster

go.mod, go.sum
Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/stolostron/backlog/issues/25276
=> upgrade hive in 2.4

.gitignore, build/run-functional-tests.sh, go.mod, go.sum
https://github.com/stolostron/backlog/issues/25252
=> [release-2.3] update hive

build/run-e2e-tests.sh, pkg/controller/autoimport/autoimport_controller.go, pkg/controller/autoimport/autoimport_controller_test.go, pkg/controller/hosted/controller.go, pkg/controller/importconfig/importconfig_controller.go, pkg/controller/importconfig/importconfig_controller_test.go, pkg/controller/importconfig/manifests/klusterlet/clusterrole_bootstrap.yaml, pkg/helpers/autoimport.go, pkg/helpers/autoimport_test.go, pkg/helpers/helpers.go, pkg/helpers/helpers_test.go, test/e2e/autoimport_test.go, test/e2e/util/util.go
=> only update the bootstrap secret when restore a cluster

go.mod
=> update golang to 1.19

pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/importconfig/cluster_info.go
=> add claim check for clusterdeployment

go.mod, go.sum
Signed-off-by: ldpliu <daliu@redhat.com>
https://github.com/stolostron/backlog/issues/26722
=> upgrade hive to mce-2.2 branch

cmd/manager/main.go, go.mod, pkg/controller/autoimport/autoimport_controller.go, pkg/controller/autoimport/autoimport_controller_test.go
=> keep the import error when retry to import a cluster

hack/copy-crds.sh, pkg/controller/importconfig/manifests/klusterlet/crds/klusterlets.crd.v1beta1.yaml
Issue reference: https://issues.redhat.com/browse/ACM-2239
=> Rollback the v1beta1 klusterlet CRD

pkg/controller/autoimport/autoimport_controller.go, pkg/controller/autoimport/autoimport_controller_test.go, pkg/controller/autoimport/manager.go, pkg/helpers/manifestwork.go, pkg/helpers/testing/testinghelpers.go, test/e2e/e2e_suite_test.go
=> check manifest work status

pkg/constants/constants.go, pkg/controller/autoimport/autoimport_controller.go, pkg/controller/autoimport/autoimport_controller_test.go, pkg/controller/autoimport/manager.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/manager.go, pkg/controller/controller.go, pkg/controller/hosted/controller.go, pkg/controller/hosted/controller_test.go, pkg/controller/hosted/manager.go, pkg/controller/importconfig/importconfig_controller.go, pkg/controller/importstatus/importstatus_controller.go, pkg/controller/importstatus/importstatus_controller_test.go, pkg/controller/importstatus/manager.go, pkg/controller/manifestwork/manifestwork_controller.go, pkg/controller/selfmanagedcluster/manager.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller_test.go, pkg/helpers/autoimport.go, pkg/helpers/autoimport_test.go, pkg/helpers/helpers.go, pkg/helpers/helpers_test.go, pkg/helpers/testing/testinghelpers.go, test/e2e/autoimport_test.go, test/e2e/e2e_suite_test.go, test/e2e/hostedcluster_test.go, test/e2e/manuallyimport_test.go, test/e2e/util/util.go
1. Extract the common logic of import into helpers.ImportHelper
2. Add a new importstatus controller to check whether the klusterlet manifestwork is available
3. Add some condition details for importing clusters
=> Add condition for cluster importing

pkg/controller/importconfig/manifests/klusterlet/operator.yaml
=> add resources for klusterlet-operator

pkg/controller/importconfig/manifests/klusterlet/operator.yaml
The related issue: https://issues.redhat.com/browse/ACM-4919
=> remove cpu limit of klusterlet

pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/cluster_info_test.go
The related issue: https://issues.redhat.com/browse/ACM-4830
=> refresh bootstrap kubeconfig once kube apiserver and CA changes

test/e2e/autoimport_test.go, test/e2e/clusterdeployment_test.go, test/e2e/e2e_suite_test.go
`wait.Poll` can't tell us the e2e fail on which line exactly. No matter what reason cause the timeout, we can only get:
```
<*errors.errorString | 0xc0001c59c0>: {
s: "timed out waiting for the condition",
}
timed out waiting for the condition
```
=> Replace `wait.Poll` to `Eventually`.

Makefile, build/clustermanager_patch.yaml, build/setup-import-controller.sh, cmd/manager/main.go, deploy/agentregistration/bootstrap_clusterrole.yaml, deploy/agentregistration/bootstrap_clusterrolebinding.yaml, deploy/agentregistration/bootstrap_serviceaccount.yaml, deploy/agentregistration/clientclusterrole.yaml, deploy/agentregistration/deploy_patch.yaml, deploy/agentregistration/kustomization.yaml, deploy/agentregistration/route.yaml, deploy/agentregistration/service.yaml, deploy/base/clusterrole.yaml, deploy/base/deployment.yaml, pkg/controller/agentregistration/server.go, pkg/controller/importconfig/agentregistration_manifests.go, pkg/controller/importconfig/agentregistration_manifests_test.go, pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/manifests/klusterlet/klusterlet.yaml, pkg/controller/importconfig/render.go, pkg/controller/importconfig/worker_default.go, pkg/controller/importconfig/worker_factory.go, pkg/controller/importconfig/worker_hosted.go, pkg/features/feature.go, sonar-project.properties, test/e2e/agentregistration_test.go, test/e2e/e2e_suite_test.go
Related issue: https://issues.redhat.com/browse/ACM-2252?focusedId=22684351&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22684351
Related PR: https://github.com/stolostron/backplane-operator/pull/476
=> Add agent-registration.

build/run-lint-check.sh
Fix oom issue https://github.com/golangci/golangci-lint/issues/3538
=> bump golangci-lint to 1.54.1

pkg/controller/importconfig/manifests/klusterlet/cluster_role.yaml
The related issue: https://issues.redhat.com/browse/ACM-6227
=> add update/patch permission of namespace to klusterlet

go.mod, go.sum, pkg/bootstrap/imagepullsecret.go, pkg/bootstrap/imagepullsecret_test.go, pkg/bootstrap/render.go, pkg/bootstrap/render_test.go, pkg/helpers/helpers.go, pkg/helpers/helpers_test.go
Fix: https://issues.redhat.com/browse/ACM-2252
=> Add KlusterletConfig support in bootstrap pkg.

build/setup-import-controller.sh, cmd/manager/main.go, deploy/base/clusterrole.yaml, deploy/base/config.open-cluster-management.io_klusterletconfig.crd.yaml, deploy/base/kustomization.yaml, go.mod, go.sum, pkg/bootstrap/render_test.go, pkg/controller/agentregistration/server.go, pkg/controller/importconfig/importconfig_controller.go, pkg/controller/importconfig/importconfig_controller_test.go, pkg/controller/importconfig/klusterletconfighandler.go, pkg/controller/importconfig/klusterletconfighandler_test.go, pkg/controller/importconfig/manager.go, pkg/source/source.go, test/e2e/e2e_suite_test.go, test/e2e/klusterletconfig_test.go
Fix: https://issues.redhat.com/browse/ACM-2252
This part of code should shared with another Epic: proxy configuration. https://issues.redhat.com/browse/ACM-6325 These 2 Epics share the same tool code. cc @elgnay
=> Add Klusterletconfig in agent-registraiton and controller.

deploy/base/config.open-cluster-management.io_klusterletconfig.crd.yaml, pkg/bootstrap/boostrapkubeconfig.go, pkg/bootstrap/bootstrapkubeconfig_test.go, pkg/controller/agentregistration/server.go, pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/cluster_info_test.go, pkg/controller/importconfig/importconfig_controller.go, pkg/controller/importconfig/importconfig_controller_test.go, pkg/helpers/testing/testinghelpers.go, sonar-project.properties, test/e2e/cleanup_test.go, test/e2e/clusterdeployment_test.go, test/e2e/e2e_suite_test.go, test/e2e/klusterletconfig_test.go, test/e2e/util/util.go
The related issue: https://issues.redhat.com/browse/ACM-6325
=> support klusterletconfig with proxyconfig

pkg/controller/importconfig/cluster_info.go
https://issues.redhat.com/browse/ACM-6918
=> fix bug when extracting api server certificate from URL

pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/cluster_info_test.go, test/e2e/managedcluter_test.go
issue: https://issues.redhat.com/browse/ACM-7422
=> [backplane-2.3] check ibm cloud exactly

pkg/bootstrap/manifests/klusterlet/cluster_role.yaml, pkg/bootstrap/manifests/klusterlet/operator.yaml
issue: https://issues.redhat.com/browse/ACM-7430
=> add rbac and env POD_NAME to fix incorrect event refobject

.tekton/managedcluster-import-controller-pull-request.yaml, .tekton/managedcluster-import-controller-push.yaml, build/Dockerfile.rhtap
issue reference: https://issues.redhat.com/browse/ACM-7262
=> Add dockerfile for rhtap

pkg/controller/importconfig/manifests/klusterlet/cluster_role.yaml
The related issue: https://issues.redhat.com/browse/ACM-6807
=> add update/patch permission of namespace to klusterlet for 2.2

pkg/bootstrap/manifests/klusterlet/operator.yaml
https://issues.redhat.com/browse/ACM-8831
=> update klusterlet operator scc

build/setup-import-controller.sh, go.mod, go.sum, pkg/controller/autoimport/autoimport_controller.go, pkg/controller/autoimport/autoimport_controller_test.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller_test.go, test/e2e/autoimport_test.go, test/e2e/e2e_suite_test.go
The related issue: https://issues.redhat.com/browse/ACM-9212
=> support to disable auto import of a managed cluster

build/Dockerfile, build/Dockerfile.rhtap
depends on: https://github.com/openshift/release/pull/48051
=> Bump up go 1.21 in dockerfiles.

deploy/base/config.open-cluster-management.io_klusterletconfig.crd.yaml, go.mod, go.sum, test/e2e/klusterletconfig_test.go
The related issue: https://issues.redhat.com/browse/ACM-9711
=> update klusterletconfig CRD

deploy/base/clusterrole.yaml, go.mod, go.sum, pkg/bootstrap/manifests/klusterlet/crds/klusterlets.crd.v1.yaml, pkg/bootstrap/manifests/klusterlet/crds/klusterlets.crd.v1beta1.yaml, pkg/bootstrap/manifests/klusterlet/klusterlet.yaml, pkg/bootstrap/manifests/klusterlet/operator.yaml, pkg/bootstrap/manifests/klusterlet/priority_class.yaml, pkg/bootstrap/render.go, pkg/constants/constants.go, pkg/controller/importconfig/importconfig_controller.go, pkg/controller/importconfig/manager.go, pkg/helpers/autoimport.go, pkg/helpers/autoimport_test.go, pkg/helpers/helpers.go, pkg/helpers/helpers_test.go, test/e2e/autoimport_test.go, test/e2e/clusterdeployment_test.go, test/e2e/e2e_suite_test.go, test/e2e/hostedcluster_test.go, test/e2e/manuallyimport_test.go, test/e2e/selfmanagedcluster_test.go
The related issue: https://issues.redhat.com/browse/ACM-6265
=> support klusterlet-priority-class

pkg/bootstrap/manifests/klusterlet/clusterrole_priority_class.yaml, pkg/bootstrap/render.go
The related issue: https://issues.redhat.com/browse/ACM-10267
=> elevate permission of work agent to create priorityclass

cmd/manager/main.go, pkg/bootstrap/boostrapkubeconfig.go, pkg/helpers/helpers.go, pkg/helpers/helpers_test.go, test/e2e/klusterletconfig_test.go
issue: https://issues.redhat.com/browse/ACM-10655
=> support deploy on non-ocp cluster

pkg/bootstrap/boostrapkubeconfig.go, pkg/bootstrap/bootstrapkubeconfig_test.go, pkg/controller/importconfig/cluster_info_test.go
https://issues.redhat.com/browse/ACM-10735
=> parse CA bundle before comparing it with the original one

pkg/helpers/klusterletconfig.go
Fixes: https://issues.redhat.com/browse/ACM-11360
=> deepcopy klusterletconfig get from lister.

pkg/controller/autoimport/manager.go, pkg/controller/clusterdeployment/manager.go, pkg/controller/selfmanagedcluster/manager.go, pkg/source/source.go, test/e2e/autoimport_test.go
The related issue: https://issues.redhat.com/browse/ACM-11477
=> trigger auto-import after removing the disable-auto-import label

pkg/helpers/helpers.go
issue reference: https://issues.redhat.com/browse/ACM-11800
update cluster importing events according to https://docs.google.com/document/d/1Lh_0I6Vu4GWrRCMCO6-CPk1MCoJ1Uq99LdAUNZ20VLw/edit
=> Update event messages for importing clusters

pkg/bootstrap/manifests/klusterlet/crds/klusterlets.crd.v1beta1.yaml
The related issue: https://issues.redhat.com/browse/ACM-12647
=> remove the unsupported default value in v1beta1 crds

pkg/controller/autoimport/apiserver_syncer.go, pkg/controller/autoimport/autoimport_syncer.go, pkg/controller/autoimport/controller.go, pkg/controller/autoimport/controller_test.go
story: https://issues.redhat.com/browse/ACM-13412
=> support get apiserverurl from auto import secret

Makefile, cmd/manager/main.go, go.mod, go.sum, pkg/bootstrap/manifests/klusterlet/bootstrap_secret.yaml, pkg/bootstrap/render.go, pkg/bootstrap/render_test.go, pkg/constants/constants.go, pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/cluster_info_test.go, pkg/controller/importconfig/importconfig_controller.go, pkg/controller/importconfig/klusterletconfighandler.go, pkg/controller/importconfig/klusterletconfighandler_test.go, pkg/controller/importconfig/manager.go, pkg/source/source.go
Fixes: https://issues.redhat.com/browse/ACM-11114
=> Add the support of "MultipleHubs" in KlusterletConfig.

pkg/controller/clusterdeployment/manager.go, test/e2e/clusterdeployment_test.go
issue: https://issues.redhat.com/browse/ACM-12756
=> fix create-via annotation not update

cmd/manager/main.go, go.mod, go.sum, pkg/bootstrap/bootstrapkubeconfig.go, pkg/bootstrap/bootstrapkubeconfig_test.go, pkg/controller/clusternamespacedeletion/controller_test.go, pkg/controller/importconfig/klusterletconfighandler.go, pkg/controller/importconfig/klusterletconfighandler_test.go, pkg/controller/importconfig/manager.go, test/e2e/util/util.go
issue reference: https://issues.redhat.com/browse/ACM-13373
=> ✨  Support using system truststore to verify the hub certificate

pkg/constants/constants.go, pkg/helpers/helpers.go, pkg/helpers/rosa.go
Issue: https://issues.redhat.com/browse/ACM-10404
=> Add the service-account way of rosa cluster importing.

pkg/helpers/helpers.go, pkg/helpers/rosa.go, pkg/helpers/rosa_test.go
Fixes: https://redhat-internal.slack.com/archives/C06TNDPUZKM/p1727813575204169?thread_ts=1727126722.361369&cid=C06TNDPUZKM
=> Fix: add cluster-id in serviceaccount auth mode.

cmd/manager/main.go
Otherwise we need to rebuild the image everytime we meet a performance issue.
What you can do to debug is:
```sh
oc patch deployment managedcluster-import-controller-v2 -n multicluster-engine --type=json -p '[{"op": "add", "path": "/spec/template/spec/containers/0/env/-", "value": {"name": "ENABLE_PPROF", "value": "true"}}]'
oc port-forward managedcluster-import-controller-v2-65fdd57c58-frs55 6060:6060
curl -o heap.out http://localhost:6060/debug/pprof/heap
go tool pprof heap.out   
```
=> Add an EV to enable/disable pprof.

pkg/bootstrap/bootstrapkubeconfig.go, pkg/bootstrap/bootstrapkubeconfig_test.go
issue reference: https://issues.redhat.com/browse/ACM-14798
=> Ignore deprecated fields if hubKubeAPIServerConfig exists

docs/rosa_cluster_import.md
Related issue: https://issues.redhat.com/browse/ACM-10404
=> Update OCM rosa import internal doc.

pkg/bootstrap/render.go, pkg/bootstrap/render_test.go
Fixes: https://issues.redhat.com/browse/ACM-14994
=> Add bootstrap-kubeconfig of current hub as the last one in the list.

.tekton/managedcluster-import-controller-addon-mce-25-pull-request.yaml, .tekton/managedcluster-import-controller-addon-mce-25-push.yaml
This update configures the SAST task to upload SARIF results to quay.io for
long-term storage
Related: 
- https://issues.redhat.com/browse/KONFLUX-3663
- https://issues.redhat.com/browse/KONFLUX-2263
=> fix(KONFLUX-3663): format PipelineRun files and upload SAST results

pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/cluster_info_test.go
Fix: https://issues.redhat.com/browse/ACM-15042
=> 🐛 [backplane-2.6] fix validate empty CA issue

pkg/controller/csr/csr_controller.go, pkg/controller/csr/csr_controller_test.go, pkg/controller/csr/manager.go
…eck if a csr is from flightctl device)
=> Refactor csr controller to prepare extend more checks(for example, check if a csr is from flightctl device)

cmd/manager/main.go
fix issue: https://issues.redhat.com/browse/ACM-15246
=> add qps and burst options

go.mod, go.sum
https://issues.redhat.com/browse/ACM-16313
=> Upgrade hive apis in Train 22

pkg/controller/importstatus/importstatus_controller.go
issue: https://issues.redhat.com/browse/ACM-17669
=> Only check if klusterlet to determine the cluster importing status

pkg/controller/clusternamespacedeletion/controller.go, pkg/controller/managedcluster/managedcluster_controller.go, pkg/controller/managedcluster/manager.go
issue: https://issues.redhat.com/browse/ACM-15965
=> delete cluster ns if there is no finalizer

.tekton/managedcluster-import-controller-addon-mce-28-pull-request.yaml, .tekton/managedcluster-import-controller-addon-mce-28-push.yaml
This PR:
- Update konflux CEL from main to backplane-2.8
=> :seedling: [backplane-2.8] update konflux files

pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go, pkg/helpers/autoimport.go, pkg/helpers/autoimport_test.go
The related issue: https://issues.redhat.com/browse/ACM-18991
=> retry forever when importing provisioned cluster & local-cluster fails

go.sum, pkg/constants/constants.go, pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/importconfig_controller_test.go, pkg/controller/manifestwork/manifestwork_controller.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller_test.go, pkg/helpers/helpers.go
story: https://issues.redhat.com/browse/ACM-18955
=> Remove crdv 1beta1

pkg/controller/hosted/controller.go, pkg/controller/manifestwork/manifestwork_controller.go
add the gc annotation to the manifestWorks before enable the resource-cleanup feature gate
=> add gc priority annotation to the manifestWorks

.tekton/managedcluster-import-controller-addon-mce-29-pull-request.yaml, .tekton/managedcluster-import-controller-addon-mce-29-push.yaml, build/Dockerfile.rhtap
Fixes: https://redhat-internal.slack.com/archives/C06TJJ3E0MU/p1746121455068529
=> Fix konflux issue.

pkg/constants/constants.go, pkg/controller/autoimport/autoimport_controller.go, pkg/controller/autoimport/autoimport_controller_test.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go, pkg/helpers/autoimport.go, pkg/helpers/autoimport_test.go, test/e2e/autoimport_test.go, test/e2e/util/util.go
The related issue: https://issues.redhat.com/browse/ACM-20121
=> remove the auto-import retry limit

pkg/bootstrap/bootstrapkubeconfig.go, pkg/bootstrap/bootstrapkubeconfig_test.go, pkg/bootstrap/render.go, pkg/controller/csr/csr_controller.go, pkg/controller/csr/csr_controller_test.go, pkg/controller/importconfig/cluster_info.go, pkg/helpers/csr.go, pkg/helpers/csr_test.go
issue: https://issues.redhat.com/browse/ACM-20645
=> fix userName in csr is incorrect if cluster name is long

cmd/manager/main.go, go.mod, go.sum, pkg/constants/constants.go, pkg/controller/autoimport/autoimport_controller.go, pkg/controller/autoimport/autoimport_controller_test.go, pkg/controller/autoimport/manager.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/manager.go, pkg/controller/controller.go, pkg/controller/selfmanagedcluster/manager.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller_test.go, pkg/helpers/autoimport.go, pkg/helpers/autoimport_test.go, pkg/helpers/testing/testinghelpers.go, pkg/source/source.go, test/e2e/autoimport_test.go, test/e2e/clusterdeployment_test.go, test/e2e/e2e_suite_test.go, test/e2e/klusterletconfig_test.go, test/e2e/selfmanagedcluster_test.go, test/e2e/util/util.go, vendor/github.com/stolostron/cluster-lifecycle-api/constants/constants.go, vendor/modules.txt
The related issue: https://issues.redhat.com/browse/ACM-20124
=> support AutoImportStrategy

pkg/helpers/autoimport.go
- Removed the applyResourcesFunc field from the ImportHelper struct.
- Updated the NewImportHelper function to reflect the removal of applyResourcesFunc.
- Renamed defaultApplyResourcesFunc to applyResourcesFunc and adjusted its usage in the Import method.
=> Refactor ImportHelper: Remove applyResourcesFunc field and update related methods

.tekton/managedcluster-import-controller-addon-mce-29-pull-request.yaml, .tekton/managedcluster-import-controller-addon-mce-29-push.yaml
This PR:
- Formatting all tekton files
- Update konflux CEL from main to backplane-2.9
=> :seedling: [backplane-2.9] update konflux files

pkg/constants/constants.go, pkg/controller/clusternamespacedeletion/controller.go, pkg/controller/clusternamespacedeletion/controller_test.go
story: https://issues.redhat.com/browse/ACM-22336
=> add an annotation to prevent the cluster ns from being deleted

docs/clusterapi_cluster_import.md, pkg/bootstrap/render.go, pkg/bootstrap/render_test.go, pkg/constants/constants.go, pkg/controller/agentregistration/server.go, pkg/controller/autoimport/autoimport_controller.go, pkg/controller/autoimport/autoimport_controller_test.go, pkg/controller/autoimport/manager.go, pkg/controller/clusterdeployment/clusterdeployment_controller.go, pkg/controller/clusterdeployment/clusterdeployment_controller_test.go, pkg/controller/clusterdeployment/manager.go, pkg/controller/controller.go, pkg/controller/importconfig/cluster_info.go, pkg/controller/importconfig/importconfig_controller.go, pkg/controller/importconfig/importconfig_controller_test.go, pkg/controller/importconfig/manager.go, pkg/controller/selfmanagedcluster/manager.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go, pkg/controller/selfmanagedcluster/selfmanagedcluster_controller_test.go, pkg/helpers/autoimport.go, pkg/helpers/autoimport_test.go, pkg/helpers/helpers.go, pkg/helpers/helpers_test.go, pkg/helpers/importcontrollerconfig.go, pkg/helpers/importcontrollerconfig_test.go, pkg/helpers/testing/testinghelpers.go, test/e2e/e2e_suite_test.go, test/e2e/managedcluster_test.go, test/e2e/util/util.go
story: https://issues.redhat.com/browse/ACM-22961
=> generate cluster import config secret
