- go.mod
https://github.com/open-cluster-management/backlog/issues/11916
> Upgrade to go1.16

- pkg/controller/manifestwork/manifestwork_controller.go
> [release-2.4] avoid to add finalizer to manifestworks if the cluster is deleting

- build/golangci.yml
fix lint:
```
╰─# make lint                                                                                                                      1 ↵
build/run-lint-check.sh
Running linting tool ...
ERRO Can't read config: can't read viper config: While parsing config: yaml: unmarshal errors:
line 198: mapping key "issues" already defined at line 27
make: *** [lint] Error 3
```
> fix ci lint

- cmd/manager/main.go
issue reference: https://github.com/stolostron/backlog/issues/26609
- Enable flags for kubeconfig and logs
- add a `leader-election-namespace` to make it possible to run the import controller locally
Before the change:
```
╰─$ ./build/_output/manager --help
Usage of ./build/_output/manager:
--feature-gates mapStringBool   A set of key=value pairs that describe feature gates for alpha/experimental features. Options are:
AllAlpha=true|false (ALPHA - default=false)
AllBeta=true|false (BETA - default=false)
KlusterletHostedMode=true|false (ALPHA - default=true)
pflag: help requested
```
After the change:
```
╰─$ ./build/_output/manager --help
Usage of ./build/_output/manager:
--add-dir-header                   If true, adds the file directory to the …
```
> Enable flags for kubeconfig and logs

- test/e2e/managedcluter_test.go
Each case should run in serial mode, because they are using the same global var :
https://github.com/stolostron/managedcluster-import-controller/blob/fc6c6ac4abbbf4c46c76c24bae101d1edefb2972/test/e2e/managedcluter_test.go#L25
> Fix prow e2e flaky error.

- pkg/controller/importconfig/manifests/klusterlet/operator.yaml
From this doc: https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/1417
OCP 4.10 doesn't support `seccomputeProfile`, remove it.
> Fix: remove seccomputeProfile to support ocp 4.10.

- pkg/constants/constants.go
- pkg/controller/managedcluster/managedcluster_controller.go
This is part of https://issues.redhat.com/browse/ACM-6547 to preserve `open-cluster-management/created-via: hypershift` annotation which is set by the hypershift hosted cluster auto-import controller.
> preserve created-via hypershift annotation

- pkg/bootstrap/boostrapkubeconfig.go
- pkg/bootstrap/bootstrapkubeconfig_test.go
If a cluster is provisioned on a baremetal, and not IBM Cloud, but with IBM domain, the node.spec.providerID would be like `baremetalhost:///openshift-machine-api/worker.test.aa.bb.ibm.com/123`, it should not be considered as an IBM cloud cluster.
> check ibm cloud exactly

- deploy/base/config.open-cluster-management.io_klusterletconfig.crd.yaml
- go.mod
- go.sum
- pkg/bootstrap/boostrapkubeconfig.go
- pkg/bootstrap/bootstrapkubeconfig_test.go
- pkg/controller/importconfig/cluster_info.go
- pkg/controller/importconfig/cluster_info_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/klusterletconfig_test.go
The related issue: https://issues.redhat.com/browse/ACM-9559
> support custom API server address & CA bundle

- pkg/bootstrap/imagepullsecret.go
- pkg/bootstrap/imagepullsecret_test.go
- pkg/bootstrap/render.go
- pkg/bootstrap/render_test.go
Fixes: https://issues.redhat.com/browse/ACM-9759
> Create Empty Image Pull Secret when no default image pull secret specified.

- pkg/bootstrap/manifests/klusterlet/priority_class.yaml
Add default `preemptionPolicy` value `PreemptLowerPriority` for the priority class, otherwise every time applying this resource, it is regarded as changed since the existing preemptionPolicy is PreemptLowerPriority, but the required preemptionPolicy is nil. see [here](https://github.com/stolostron/managedcluster-import-controller/blob/4ae27f63d570ccb49d8f53fb22420078577cb6c9/pkg/helpers/helpers.go#L619), and this will result in the cluster condition changing back and forth(ManagedClusterImporting & ManagedClusterImported).
```
equality.Semantic.DeepEqual(existing.PreemptionPolicy, required.PreemptionPolicy) 
```
> 🐛 Add default preemptionPolicy for priority class

- go.mod
- go.sum
- pkg/constants/constants.go
- pkg/controller/agentregistration/server.go
- pkg/controller/importconfig/importconfig_controller.go
- pkg/controller/importconfig/klusterletconfighandler.go
- pkg/controller/importconfig/klusterletconfighandler_test.go
- pkg/helpers/klusterletconfig.go
- pkg/helpers/klusterletconfig_test.go
Story: https://issues.redhat.com/browse/ACM-10074
We add global klusterletconfig related code in 2 places:
* agentregistration server
* import-config-controller
Currently we are only required to support 1 special "global" klustereletconfig, but in the future if we want to support multiple klusterletconfig, we need to refactor more.
> Add "global" KlusterletConfig Support.

- pkg/bootstrap/bootstrapkubeconfig.go
- pkg/bootstrap/bootstrapkubeconfig_test.go
- pkg/constants/constants.go
- pkg/controller/agentregistration/server.go
- pkg/controller/importconfig/importconfig_controller.go
Fix: https://issues.redhat.com/browse/ACM-12277
In this PR, we change agent-registration to return a short-term bootstrapkubeconfig secret if the `duration` param in the URL is set, for example:
```sh
curl --cacert ca.crt -H "Authorization: Bearer $token" [https://$agent_registration_host/agent-registration/manifests/cluster-e2e-test-agent?klusterletconfig\=default\&expiration\=4h](https://$agent_registration_host/agent-registration/manifests/cluster-e2e-test-agent?klusterletconfig=default&duration=4h)
```
> Return short-term token in agent-regstration endpoint.

- pkg/controller/autoimport/autoimport_controller.go
- pkg/controller/autoimport/autoimport_controller_test.go
- pkg/controller/autoimport/manager.go
- pkg/controller/importstatus/importstatus_controller.go
- pkg/controller/manifestwork/manifestwork_controller.go
- pkg/source/source.go
- test/e2e/e2e_suite_test.go
The first error msg is like:
```
Importing a managed cluster with auto-import-secret Should not import the cluster if auto-import is disabled
/home/runner/work/managedcluster-import-controller/managedcluster-import-controller/test/e2e/autoimport_test.go:67
STEP: Create managed cluster namespace autoimport-test-vj4vh6 @ 08/06/24 15:17:32.354
STEP: Create auto-import-secret for managed cluster autoimport-test-vj4vh6 with kubeconfig
---
[FAILED] in [It] - /home/runner/work/managedcluster-import-controller/managedcluster-import-controller/test/e2e/e2e_suite_test.go:557 @ 08/06/24 15:25:34.43
STEP: Delete the managed cluster autoimport-test-vj4vh6 @ 08/06/24 15:25:34.43
STEP: Should delete the managed cluster autoimport-test-vj4vh6 @ 08/06/24 15:25:34.435
DEBUG: spending time: 1.01 seconds …
```
> Fix flaky e2e error.

- pkg/controller/importconfig/manager.go
Fixes: https://issues.redhat.com/browse/ACM-14605
WatchesMetadata doesn't unmarshal the data part and save a lot of memory.
Tested with 200 managedcluster, the base memory usage(0 managed cluster) is 145Mb:
* `Watches` uses 400Mb
* `WatchesMetadata` uses 174Mb.
> Change `Watches` to `WatchesMetadata`.

- build/setup-import-controller.sh
- deploy/agentregistration/clientclusterrole.yaml
Also updated in backplane-operator: https://github.com/stolostron/backplane-operator/pull/1077
> Fix typo `regitration` to `registration`

- pkg/controller/autoimport/autoimport_controller.go
- pkg/controller/autoimport/manager.go
- pkg/controller/clusterdeployment/clusterdeployment_controller.go
- pkg/controller/clusterdeployment/manager.go
- pkg/controller/clusternamespacedeletion/controller.go
- pkg/controller/clusternamespacedeletion/manager.go
- pkg/controller/clusternamespacedeletion/suite_test.go
- pkg/controller/controller.go
- pkg/controller/csr/manager.go
- pkg/controller/hosted/controller.go
- pkg/controller/hosted/manager.go
- pkg/controller/importconfig/importconfig_controller.go
- pkg/controller/importconfig/manager.go
- pkg/controller/importstatus/importstatus_controller.go
- pkg/controller/importstatus/manager.go
- pkg/controller/managedcluster/managedcluster_controller.go
- pkg/controller/managedcluster/manager.go
- pkg/controller/manifestwork/manager.go
- pkg/controller/manifestwork/manifestwork_controller.go
- pkg/controller/selfmanagedcluster/manager.go
- pkg/controller/selfmanagedcluster/selfmanagedcluster_controller.go
Simply `AddToManager`, and:
1. When we call `Add` function, only need to input the varibles the controller actually needs. For example, csrContoller doesn't need `informer` and `recoder`, now it doesn't need put them in the `Add`'s `inputs`.
2. In the future, if we want to add customized varibles to specific controller, for example, if we want to add `flightctl flag` to csr controller, without affect other controllers.
3. Now hosted controller can handle like other controllers. Unified the code style.
> Refactor: controller `AddToManager`

- pkg/bootstrap/render.go
- pkg/helpers/helpers.go
Render files into objects and use `helper.ApplyResources` is not only needed inside the `bootstrap` repo.  
For example, in the `flightctl` case, if `flightctl` is enabled, we want to apply some resources. It would be convenient if `FilesToObjects` is a common method in the helper package.
> Move `FliesToObjects` function into the `helper` pkg.

- pkg/bootstrap/bootstrapkubeconfig.go
- pkg/bootstrap/bootstrapkubeconfig_test.go
- pkg/controller/agentregistration/server.go
- pkg/controller/importconfig/cluster_info.go
- pkg/controller/importconfig/cluster_info_test.go
- pkg/controller/importconfig/importconfig_controller.go
The related issue: https://issues.redhat.com/browse/ACM-15486
> refactor to simplify the bootstrap kubeconfig creation logic

- pkg/constants/constants.go
- pkg/controller/controller.go
- pkg/controller/csr/csr_controller.go
- pkg/controller/csr/csr_controller_test.go
- pkg/controller/csr/manager.go
- pkg/helpers/csr.go
- pkg/helpers/csr_test.go
There are mainly **2** changes in this PR:
**First**, the `GetClusterName` is moved from `csr-controller` to `helpers` pkg, along with some const values move to `constant` pkg.
**Second**, the `Add` function added a `extraApprovalConditions` array, to allow the `csr controller` to accept and use customized approval conditions.
---
**What I want to achieve**, is in the future, we can have more approvalConditions defined and implementated in their our pkg(for example, flightctl approve stays in the `flightctl` pkg with other flight logic code),  when we add new approval condition, the `csr controller` don't need to change much.
> Refactor: move common functions out of csr controller, into `constants` or `helpers`.

- test/e2e/autoimport_test.go
- test/e2e/cleanup_test.go
- test/e2e/e2e_suite_test.go
- test/e2e/hostedcluster_test.go
- test/e2e/klusterletconfig_test.go
- test/e2e/util/util.go
Ref: https://github.com/open-cluster-management-io/ocm/pull/727
https://issues.redhat.com/browse/ACM-15860 
- In `assertManagedClusterManifestWorksAvailable` and some cases, add the logic to check manifestwork finalizer, ensure the work agent starts working before each case. 
- In `CreateHostedManagedClusterWithShortLeaseDuration`, increase LeaseDurationSeconds to 10. Since the agent enables leader election, in some cases the agent might start slower than before, increasing the LeaseDurationSeconds to avoid force removal in `assertManagedClusterDeleted` in AfterEach.
- When `restartAgentPods`, check the agent leader to ensure the work agent works before the next step.
> fix e2e test issues when sno leader election enabled

- go.mod
- go.sum
Upgrade hive apis to latest version in Train 23
> Upgrade hive apis in Train 23

- deploy/base/clusterrole.yaml
fix the error logs 
`E0217 07:41:51.934808       1 reflector.go:158] "Unhandled Error" err="sigs.k8s.io/controller-runtime/pkg/cache/internal/informers.go:108: Failed to watch *v1beta1.Cluster: unknown (get clusters.cluster.x-k8s.io)"`
> add watch verb for capi clusters.cluster.x-k8s.io

- build/run-unit-tests.sh
Fixes issue: the https://storage.googleapis.com/kubebuilder-tools/ doesn't contain `darwin-arm64` version for `1.23.1`, so we can't run unit-test locally.
> Update Kubernetes version in run-unit-tests script to 1.30.0

- pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
- pkg/helpers/autoimport.go
- pkg/helpers/autoimport_test.go
Related issue: https://issues.redhat.com/browse/ACM-18991
> retry on kube client creation failure during auto-import

- go.mod
- go.sum
https://issues.redhat.com/browse/ACM-19235
> [backplane-2.7] bump github.com/golang-jwt/jwt/v4 to v4.5.2

- pkg/controller/managedcluster/managedcluster_controller.go
The logic for checking the created-via value in the ensureCreateViaAnnotation function has been optimized by using a map to replace multiple conditional statements.
This refactoring has the following advantages:
1. The code is more concise, eliminating the need for long conditional statements.
2. It is easier to maintain; when a new CreatedVia value needs to be added, simply add an entry to the map.
3. The logic is clearer, directly expressing the intent of "using a default value if it is not in the set of valid values."
All tests have passed to ensure functionality is normal.
> Refactor ensureCreateViaAnnotation to use a map for valid created-via values

- .tekton/managedcluster-import-controller-addon-mce-29-pull-request.yaml
- .tekton/managedcluster-import-controller-addon-mce-29-push.yaml
This PR adds multiarch build support to the Tekton pipeline configurations by adding support for multiple architectures: linux/x86_64, linux/arm64, linux/ppc64le, and linux/s390x. Changes include: - Updated build-platforms parameter in both pull request and push pipeline configurations - Modified both spec params and default values to include all supported architectures - Enables building container images for multiple platforms using the multi-platform controller
> Add multiarch build support to Tekton pipelines

- Makefile
In the e2e log, it shows case timeout after about 30s: 
```
[TIMEDOUT] [31.622 seconds]
```
But in our case, we configured the timeout to `5 min`: 
https://github.com/stolostron/managedcluster-import-controller/blob/cc0b7c75684f0e4bf55b91cd30a2ce7071c0a156/test/e2e/e2e_suite_test.go#L643
---
Root casue:
The error is **NOT** caused by **spec timeout**, but the **whole suite timeout.** 
By default the suite timeout is **1 hour**, as our test cases add more and more, it needs more than 1 hour, so any case that happens be running at around 1 hour, will be cancelled.
> Update: ginkgo.time to 2h. 

- go.mod
- go.sum
- pkg/bootstrap/render.go
- pkg/bootstrap/render_test.go
- pkg/controller/importconfig/klusterletconfighandler_test.go
Fixes: https://issues.redhat.com/browse/ACM-22012
Before:
```yaml
apiVersion: [operator.open-cluster-management.io/v1](http://operator.open-cluster-management.io/v1)
kind: Klusterlet
metadata:
name: "klusterlet-globalhub-import"
spec:
...
namespace: "open-cluster-management-globalhub-import"
registrationConfiguration:
bootstrapKubeConfigs:
localSecretsConfig:
kubeConfigSecrets: null
workConfiguration:
{}
nodePlacement:
```
After:
```yaml
apiVersion: operator.open-cluster-management.io/v1
kind: Klusterlet
metadata:
name: "klusterlet-globalhub-import"
spec:
...
namespace: "open-cluster-management-globalhub-import"
registrationConfiguration:
bootstrapKubeConfigs: {}
workConfiguration:
{}
nodePlacement:
```
> Fix klusterlet 2.13 CR doesn't match 2.14 CRD in globalhub's no-operator case.

- build/setup-kind-clusters.sh
This PR removes the sleep 100 line that was added as a test-only line in setup-kind-clusters.sh.
The sleep command was marked as "test only" and should not remain in the production script.
> Remove sleep 100 from setup-kind-clusters.sh

- pkg/controller/hosted/controller.go
- pkg/controller/hosted/manifests/external_managed_secret.yaml
This change adds a backup label to the external-managed-kubeconfig secret when the hosting cluster is a local cluster (has local-cluster=true label). This ensures proper backup handling for import controller secrets.
https://issues.redhat.com/browse/ACM-22972
Signed-off-by: daliu@redhat.com
> Add backup label for external managed kubeconfig in local clusters

- .tekton/managedcluster-import-controller-addon-mce-28-pull-request.yaml
- .tekton/managedcluster-import-controller-addon-mce-28-push.yaml
This PR updates the Tekton pipeline configurations to:
- **Multi-platform build support**: Added `linux/arm64`, `linux/ppc64le`, and `linux/s390x` to the `build-platforms` parameter in both push and pull request pipelines
- **Slack notifications**: Added required Slack notification parameters (`send-slack-notification`, `konflux-application-name`, `slack-member-id`) to the push pipeline
- Extended `build-platforms` to include all required architectures
- Added `send-slack-notification: "true"`
- Added `konflux-application-name: "release-mce-28"` (matching the backplane-2.8 branch)
- Added `slack-member-id: "U01TX25RJ3B"`
- Extended `build-platforms` to include all required architectures
These changes ensure that:
- Builds will now run on multiple platforms (x86_64, arm64, ppc64le, s390x) …
> Add multi-platform build support and Slack notifications to Tekton pipelines
